module.exports = {
  DATABASE_CONNECTION: `Database connected successfully.`,
  VALIDATION_ERROR: `Validation error.`,
  DATABASE_ERROR: `Database error.`,
  EMAIL_IN_USE: `Email is already in use.`,
  ERROR_REGISTERING_USER: `Error in registering user.`,
  ERROR_FINDING_USER: `Error in finding user.`,
  REGISTERING_USER: `User registerd successfully.`,
  INTERNAL_SERVER_ERROR: `Internal server error.`,
  ERROR_FETCHING_USER: `Error in fetching user.`,
  RETRIEVED_USER: `User retrieved successfully.`,
  USER_NOT_FOUND: `User not found.`,
  LOGIN_SUCCESS: `Login successfull.`,
  INVALID_CERIDIAN: `Invalid ceridian.`,
  OTP_SENT: `OTP sent successfully.`,
  OTP_NOT_SENT: `Failed to sent otp.`,
};
